// src/lib/timezones-data.ts
// NexCal v3.0 — Comprehensive global timezone database mapping countries, capitals, and standard IANA timezone IDs.

export interface TimezoneEntry {
  country: string;
  capital: string;
  tzId: string;
}

export const timezonesData: TimezoneEntry[] = [
  { country: "UTC", capital: "Coordinated Universal Time", tzId: "UTC" },
  { country: "Afghanistan", capital: "Kabul", tzId: "Asia/Kabul" },
  { country: "Albania", capital: "Tirana", tzId: "Europe/Tirane" },
  { country: "Algeria", capital: "Algiers", tzId: "Africa/Algiers" },
  { country: "Andorra", capital: "Andorra la Vella", tzId: "Europe/Andorra" },
  { country: "Angola", capital: "Luanda", tzId: "Africa/Luanda" },
  { country: "Antigua and Barbuda", capital: "Saint John's", tzId: "America/Antigua" },
  { country: "Argentina", capital: "Buenos Aires", tzId: "America/Argentina/Buenos_Aires" },
  { country: "Armenia", capital: "Yerevan", tzId: "Asia/Yerevan" },
  { country: "Australia", capital: "Canberra", tzId: "Australia/Canberra" },
  { country: "Australia", capital: "Sydney", tzId: "Australia/Sydney" },
  { country: "Australia", capital: "Melbourne", tzId: "Australia/Melbourne" },
  { country: "Australia", capital: "Perth", tzId: "Australia/Perth" },
  { country: "Austria", capital: "Vienna", tzId: "Europe/Vienna" },
  { country: "Azerbaijan", capital: "Baku", tzId: "Asia/Baku" },
  { country: "Bahamas", capital: "Nassau", tzId: "America/Nassau" },
  { country: "Bahrain", capital: "Manama", tzId: "Asia/Bahrain" },
  { country: "Bangladesh", capital: "Dhaka", tzId: "Asia/Dhaka" },
  { country: "Barbados", capital: "Bridgetown", tzId: "America/Barbados" },
  { country: "Belarus", capital: "Minsk", tzId: "Europe/Minsk" },
  { country: "Belgium", capital: "Brussels", tzId: "Europe/Brussels" },
  { country: "Belize", capital: "Belmopan", tzId: "America/Belmopan" },
  { country: "Benin", capital: "Porto-Novo", tzId: "Africa/Porto-Novo" },
  { country: "Bhutan", capital: "Thimphu", tzId: "Asia/Thimphu" },
  { country: "Bolivia", capital: "Sucre", tzId: "America/La_Paz" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", tzId: "Europe/Sarajevo" },
  { country: "Botswana", capital: "Gaborone", tzId: "Africa/Gaborone" },
  { country: "Brazil", capital: "Brasilia", tzId: "America/Sao_Paulo" },
  { country: "Brunei", capital: "Bandar Seri Begawan", tzId: "Asia/Brunei" },
  { country: "Bulgaria", capital: "Sofia", tzId: "Europe/Sofia" },
  { country: "Burkina Faso", capital: "Ouagadougou", tzId: "Africa/Ouagadougou" },
  { country: "Burundi", capital: "Gitega", tzId: "Africa/Bujumbura" },
  { country: "Cabo Verde", capital: "Praia", tzId: "Atlantic/Cape_Verde" },
  { country: "Cambodia", capital: "Phnom Penh", tzId: "Asia/Phnom_Penh" },
  { country: "Cameroon", capital: "Yaounde", tzId: "Africa/Douala" },
  { country: "Canada", capital: "Ottawa", tzId: "America/Toronto" },
  { country: "Canada", capital: "Vancouver", tzId: "America/Vancouver" },
  { country: "Canada", capital: "Halifax", tzId: "America/Halifax" },
  { country: "Canada", capital: "Winnipeg", tzId: "America/Winnipeg" },
  { country: "Canada", capital: "Edmonton", tzId: "America/Edmonton" },
  { country: "Central African Republic", capital: "Bangui", tzId: "Africa/Bangui" },
  { country: "Chad", capital: "N'Djamena", tzId: "Africa/Ndjamena" },
  { country: "Chile", capital: "Santiago", tzId: "America/Santiago" },
  { country: "China", capital: "Beijing", tzId: "Asia/Shanghai" },
  { country: "Colombia", capital: "Bogota", tzId: "America/Bogota" },
  { country: "Comoros", capital: "Moroni", tzId: "Indian/Comoro" },
  { country: "Congo", capital: "Brazzaville", tzId: "Africa/Brazzaville" },
  { country: "Costa Rica", capital: "San Jose", tzId: "America/Costa_Rica" },
  { country: "Croatia", capital: "Zagreb", tzId: "Europe/Zagreb" },
  { country: "Cuba", capital: "Havana", tzId: "America/Havana" },
  { country: "Cyprus", capital: "Nicosia", tzId: "Asia/Nicosia" },
  { country: "Czechia", capital: "Prague", tzId: "Europe/Prague" },
  { country: "Denmark", capital: "Copenhagen", tzId: "Europe/Copenhagen" },
  { country: "Djibouti", capital: "Djibouti", tzId: "Africa/Djibouti" },
  { country: "Dominica", capital: "Roseau", tzId: "America/Dominica" },
  { country: "Dominican Republic", capital: "Santo Domingo", tzId: "America/Santo_Domingo" },
  { country: "Ecuador", capital: "Quito", tzId: "America/Guayaquil" },
  { country: "Egypt", capital: "Cairo", tzId: "Africa/Cairo" },
  { country: "El Salvador", capital: "San Salvador", tzId: "America/El_Salvador" },
  { country: "Equatorial Guinea", capital: "Malabo", tzId: "Africa/Malabo" },
  { country: "Eritrea", capital: "Asmara", tzId: "Africa/Asmara" },
  { country: "Estonia", capital: "Tallinn", tzId: "Europe/Tallinn" },
  { country: "Eswatini", capital: "Mbabane", tzId: "Africa/Mbabane" },
  { country: "Ethiopia", capital: "Addis Ababa", tzId: "Africa/Addis_Ababa" },
  { country: "Fiji", capital: "Suva", tzId: "Pacific/Fiji" },
  { country: "Finland", capital: "Helsinki", tzId: "Europe/Helsinki" },
  { country: "France", capital: "Paris", tzId: "Europe/Paris" },
  { country: "Gabon", capital: "Libreville", tzId: "Africa/Libreville" },
  { country: "Gambia", capital: "Banjul", tzId: "Africa/Banjul" },
  { country: "Georgia", capital: "Tbilisi", tzId: "Asia/Tbilisi" },
  { country: "Germany", capital: "Berlin", tzId: "Europe/Berlin" },
  { country: "Ghana", capital: "Accra", tzId: "Africa/Accra" },
  { country: "Greece", capital: "Athens", tzId: "Europe/Athens" },
  { country: "Grenada", capital: "St. George's", tzId: "America/Grenada" },
  { country: "Guatemala", capital: "Guatemala City", tzId: "America/Guatemala" },
  { country: "Guinea", capital: "Conakry", tzId: "Africa/Conakry" },
  { country: "Guinea-Bissau", capital: "Bissau", tzId: "Africa/Bissau" },
  { country: "Guyana", capital: "Georgetown", tzId: "America/Guyana" },
  { country: "Haiti", capital: "Port-au-Prince", tzId: "America/Port-au-Prince" },
  { country: "Honduras", capital: "Tegucigalpa", tzId: "America/Tegucigalpa" },
  { country: "Hungary", capital: "Budapest", tzId: "Europe/Budapest" },
  { country: "Iceland", capital: "Reykjavik", tzId: "Atlantic/Reykjavik" },
  { country: "India", capital: "New Delhi", tzId: "Asia/Kolkata" },
  { country: "Indonesia", capital: "Jakarta", tzId: "Asia/Jakarta" },
  { country: "Indonesia", capital: "Nusantara (Makassar)", tzId: "Asia/Makassar" },
  { country: "Indonesia", capital: "Jayapura", tzId: "Asia/Jayapura" },
  { country: "Iran", capital: "Tehran", tzId: "Asia/Tehran" },
  { country: "Iraq", capital: "Baghdad", tzId: "Asia/Baghdad" },
  { country: "Ireland", capital: "Dublin", tzId: "Europe/Dublin" },
  { country: "Israel", capital: "Jerusalem", tzId: "Asia/Jerusalem" },
  { country: "Italy", capital: "Rome", tzId: "Europe/Rome" },
  { country: "Jamaica", capital: "Kingston", tzId: "America/Jamaica" },
  { country: "Japan", capital: "Tokyo", tzId: "Asia/Tokyo" },
  { country: "Jordan", capital: "Amman", tzId: "Asia/Amman" },
  { country: "Kazakhstan", capital: "Astana", tzId: "Asia/Almaty" },
  { country: "Kenya", capital: "Nairobi", tzId: "Africa/Nairobi" },
  { country: "Kiribati", capital: "Tarawa", tzId: "Pacific/Tarawa" },
  { country: "Kosovo", capital: "Pristina", tzId: "Europe/Belgrade" },
  { country: "Kuwait", capital: "Kuwait City", tzId: "Asia/Kuwait" },
  { country: "Kyrgyzstan", capital: "Bishkek", tzId: "Asia/Bishkek" },
  { country: "Laos", capital: "Vientiane", tzId: "Asia/Vientiane" },
  { country: "Latvia", capital: "Riga", tzId: "Europe/Riga" },
  { country: "Lebanon", capital: "Beirut", tzId: "Asia/Beirut" },
  { country: "Lesotho", capital: "Maseru", tzId: "Africa/Maseru" },
  { country: "Liberia", capital: "Monrovia", tzId: "Africa/Monrovia" },
  { country: "Libya", capital: "Tripoli", tzId: "Africa/Tripoli" },
  { country: "Liechtenstein", capital: "Vaduz", tzId: "Europe/Vaduz" },
  { country: "Lithuania", capital: "Vilnius", tzId: "Europe/Vilnius" },
  { country: "Luxembourg", capital: "Luxembourg", tzId: "Europe/Luxembourg" },
  { country: "Madagascar", capital: "Antananarivo", tzId: "Africa/Nairobi" },
  { country: "Malawi", capital: "Lilongwe", tzId: "Africa/Blantyre" },
  { country: "Malaysia", capital: "Kuala Lumpur", tzId: "Asia/Kuala_Lumpur" },
  { country: "Maldives", capital: "Male", tzId: "Indian/Maldives" },
  { country: "Mali", capital: "Bamako", tzId: "Africa/Bamako" },
  { country: "Malta", capital: "Valletta", tzId: "Europe/Malta" },
  { country: "Marshall Islands", capital: "Majuro", tzId: "Pacific/Majuro" },
  { country: "Mauritania", capital: "Nouakchott", tzId: "Africa/Nouakchott" },
  { country: "Mauritius", capital: "Port Louis", tzId: "Indian/Mauritius" },
  { country: "Mexico", capital: "Mexico City", tzId: "America/Mexico_City" },
  { country: "Micronesia", capital: "Palikir", tzId: "Pacific/Pohnpei" },
  { country: "Moldova", capital: "Chisinau", tzId: "Europe/Chisinau" },
  { country: "Monaco", capital: "Monaco", tzId: "Europe/Monaco" },
  { country: "Mongolia", capital: "Ulaanbaatar", tzId: "Asia/Ulaanbaatar" },
  { country: "Montenegro", capital: "Podgorica", tzId: "Europe/Podgorica" },
  { country: "Morocco", capital: "Rabat", tzId: "Africa/Casablanca" },
  { country: "Mozambique", capital: "Maputo", tzId: "Africa/Maputo" },
  { country: "Myanmar", capital: "Naypyidaw", tzId: "Asia/Yangon" },
  { country: "Namibia", capital: "Windhoek", tzId: "Africa/Windhoek" },
  { country: "Nauru", capital: "Yaren", tzId: "Pacific/Nauru" },
  { country: "Nepal", capital: "Kathmandu", tzId: "Asia/Kathmandu" },
  { country: "Netherlands", capital: "Amsterdam", tzId: "Europe/Amsterdam" },
  { country: "New Zealand", capital: "Wellington", tzId: "Pacific/Auckland" },
  { country: "Nicaragua", capital: "Managua", tzId: "America/Managua" },
  { country: "Niger", capital: "Niamey", tzId: "Africa/Niamey" },
  { country: "Nigeria", capital: "Abuja", tzId: "Africa/Lagos" },
  { country: "North Korea", capital: "Pyongyang", tzId: "Asia/Pyongyang" },
  { country: "North Macedonia", capital: "Skopje", tzId: "Europe/Skopje" },
  { country: "Norway", capital: "Oslo", tzId: "Europe/Oslo" },
  { country: "Oman", capital: "Muscat", tzId: "Asia/Muscat" },
  { country: "Pakistan", capital: "Islamabad", tzId: "Asia/Karachi" },
  { country: "Palau", capital: "Ngerulmud", tzId: "Pacific/Palau" },
  { country: "Palestine", capital: "Ramallah", tzId: "Asia/Hebron" },
  { country: "Panama", capital: "Panama City", tzId: "America/Panama" },
  { country: "Papua New Guinea", capital: "Port Moresby", tzId: "Pacific/Port_Moresby" },
  { country: "Paraguay", capital: "Asuncion", tzId: "America/Asuncion" },
  { country: "Peru", capital: "Lima", tzId: "America/Lima" },
  { country: "Philippines", capital: "Manila", tzId: "Asia/Manila" },
  { country: "Poland", capital: "Warsaw", tzId: "Europe/Warsaw" },
  { country: "Portugal", capital: "Lisbon", tzId: "Europe/Lisbon" },
  { country: "Qatar", capital: "Doha", tzId: "Asia/Qatar" },
  { country: "Romania", capital: "Bucharest", tzId: "Europe/Bucharest" },
  { country: "Russia", capital: "Moscow", tzId: "Europe/Moscow" },
  { country: "Russia", capital: "Vladivostok", tzId: "Asia/Vladivostok" },
  { country: "Rwanda", capital: "Kigali", tzId: "Africa/Kigali" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", tzId: "America/St_Kitts" },
  { country: "Saint Lucia", capital: "Castries", tzId: "America/St_Lucia" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", tzId: "America/St_Vincent" },
  { country: "Samoa", capital: "Apia", tzId: "Pacific/Apia" },
  { country: "San Marino", capital: "San Marino", tzId: "Europe/San_Marino" },
  { country: "Sao Tome and Principe", capital: "Sao Tome", tzId: "Africa/Sao_Tome" },
  { country: "Saudi Arabia", capital: "Riyadh", tzId: "Asia/Riyadh" },
  { country: "Senegal", capital: "Dakar", tzId: "Africa/Dakar" },
  { country: "Serbia", capital: "Belgrade", tzId: "Europe/Belgrade" },
  { country: "Seychelles", capital: "Victoria", tzId: "Indian/Mahe" },
  { country: "Sierra Leone", capital: "Freetown", tzId: "Africa/Freetown" },
  { country: "Singapore", capital: "Singapore", tzId: "Asia/Singapore" },
  { country: "Slovakia", capital: "Bratislava", tzId: "Europe/Bratislava" },
  { country: "Slovenia", capital: "Ljubljana", tzId: "Europe/Ljubljana" },
  { country: "Solomon Islands", capital: "Honiara", tzId: "Pacific/Guadalcanal" },
  { country: "Somalia", capital: "Mogadishu", tzId: "Africa/Mogadishu" },
  { country: "South Africa", capital: "Pretoria", tzId: "Africa/Johannesburg" },
  { country: "South Korea", capital: "Seoul", tzId: "Asia/Seoul" },
  { country: "South Sudan", capital: "Juba", tzId: "Africa/Juba" },
  { country: "Spain", capital: "Madrid", tzId: "Europe/Madrid" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", tzId: "Asia/Colombo" },
  { country: "Sudan", capital: "Khartoum", tzId: "Africa/Khartoum" },
  { country: "Suriname", capital: "Paramaribo", tzId: "America/Paramaribo" },
  { country: "Sweden", capital: "Stockholm", tzId: "Europe/Stockholm" },
  { country: "Switzerland", capital: "Bern", tzId: "Europe/Zurich" },
  { country: "Syria", capital: "Damascus", tzId: "Asia/Damascus" },
  { country: "Taiwan", capital: "Taipei", tzId: "Asia/Taipei" },
  { country: "Tajikistan", capital: "Dushanbe", tzId: "Asia/Dushanbe" },
  { country: "Tanzania", capital: "Dodoma", tzId: "Africa/Dar_es_Salaam" },
  { country: "Thailand", capital: "Bangkok", tzId: "Asia/Bangkok" },
  { country: "Timor-Leste", capital: "Dili", tzId: "Asia/Dili" },
  { country: "Togo", capital: "Lome", tzId: "Africa/Lome" },
  { country: "Tonga", capital: "Nuku'alofa", tzId: "Pacific/Tongatapu" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", tzId: "America/Port_of_Spain" },
  { country: "Tunisia", capital: "Tunis", tzId: "Africa/Tunis" },
  { country: "Turkey", capital: "Ankara", tzId: "Europe/Istanbul" },
  { country: "Turkmenistan", capital: "Ashgabat", tzId: "Asia/Ashgabat" },
  { country: "Tuvalu", capital: "Funafuti", tzId: "Pacific/Funafuti" },
  { country: "Uganda", capital: "Kampala", tzId: "Africa/Kampala" },
  { country: "Ukraine", capital: "Kyiv", tzId: "Europe/Kyiv" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", tzId: "Asia/Dubai" },
  { country: "United Kingdom", capital: "London", tzId: "Europe/London" },
  { country: "United States", capital: "Washington D.C.", tzId: "America/New_York" },
  { country: "United States", capital: "Los Angeles (West Coast)", tzId: "America/Los_Angeles" },
  { country: "United States", capital: "Chicago (Midwest)", tzId: "America/Chicago" },
  { country: "United States", capital: "Denver (Mountain)", tzId: "America/Denver" },
  { country: "United States", capital: "Honolulu (Hawaii)", tzId: "Pacific/Honolulu" },
  { country: "Uruguay", capital: "Montevideo", tzId: "America/Montevideo" },
  { country: "Uzbekistan", capital: "Tashkent", tzId: "Asia/Tashkent" },
  { country: "Vanuatu", capital: "Port Vila", tzId: "Pacific/Efate" },
  { country: "Vatican City", capital: "Vatican City", tzId: "Europe/Vatican" },
  { country: "Venezuela", capital: "Caracas", tzId: "America/Caracas" },
  { country: "Vietnam", capital: "Hanoi", tzId: "Asia/Ho_Chi_Minh" },
  { country: "Yemen", capital: "Sana'a", tzId: "Asia/Aden" },
  { country: "Zambia", capital: "Lusaka", tzId: "Africa/Lusaka" },
  { country: "Zimbabwe", capital: "Harare", tzId: "Africa/Harare" }
];
